version: '3.8' # Versão do Docker Compose

services:
  postgres:
    image: postgres
    container_name: pagamentos-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pagamentos-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
